### PR TITLE
will remove FOUC in chrome >29

### PR DESCRIPTION
**Pull request by thebyrd**

### CODE REVIEW

**Comment by sjkaliski** [comment]
lgtm

**Comment by sjkaliski** [comment]
is this polymer only?

**Comment by AbhiAgarwal** [comment]
https://www.polymer-project.org/articles/styling-elements.html

**Comment by thebyrd** [comment]
:unresolved is supported natively in Chrome 29, polymer just has polyfills for it

**Comment by sjkaliski** [comment]
:golf: :clap:

**Comment by ethanresnick** [comment]
@thebyrd but i'm pretty sure the :unresolved pseudo-class that polymer is polyfilling is still only something that applies to custom elements. it's [part of](https://w3c.github.io/webcomponents/spec/custom/#unresolved-element-pseudoclass) the custom elements spec. and we're not using custom elements, so i'm pretty sure it doesn't apply here.

**Comment by ethanresnick** [comment]
Closing since we're not using custom elements

**Pull request closed without merging**
